[build-system]
requires = ["maturin>=0.12"]
build-backend = "maturin"

[project]
name = "crystsymm"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]